// Package runtime defines the runtime data structures that are
// created by the rule_compiler.

package rete

import "reflect"


type Rule interface {
	Name() string                            // defimpl:"read name"

	// RuleRunctionName is the name of the function that is called by
	// the Caller() function and implements the rule.
	RuleFunctionName() string              // defimpl:"read ruleFunctionName"

	// Installer adds the implementation of the rule to the rete
	// represented by this given root node.
	Installer() func(Node)              // defimpl:"read installer"

	// Caller is the function that destructures the join results and
	// calls the rule function.
	Caller() func(Node, []interface{})     // defimpl:"read caller"

	// ParamTypes lists the types of the rule's parameters.
	ParamTypes() []reflect.Type               // defimpl:"read paramTypes"

	// DoParamTypes applies the function to each parameter type of
	// the rule, terminating early if the function returns nil.
	DoParamTypes(func(reflect.Type) bool)     // defimpl:"iterate paramTypes"

	// EmitTypess lists the types of objects that the rule can Emit.
	EmitTypes() []reflect.Type                 // defimpl:"read emitTypes"

	// DoEmitTypes applies the function to each emit type of
	// the rule, terminating early if the function returns nil.
	DoEmitTypes(func(reflect.Type) bool)     // defimpl:"iterate emitTypes"

	// Emits returns true if the specified type is emitted by the Rule.
	Emits(reflect.Type) bool
}


// AllRules is a catalog describing all compiled rules that are loaded
// into the program
var AllRules []Rule = []Rule{}


// AddRule adds a rule to AllRules.  It is called by the code that is
// generated by the rule_compiler.
func AddRule(name string,
		ruleFunctionName string,
		installer func(Node),
		caller func(Node, []interface{}),
		paramTypes []reflect.Type,
		emitTypes []reflect.Type) Rule {
	// Body
	rule := &RuleImpl{
		name: name,
		ruleFunctionName: ruleFunctionName,
		installer: installer,
		caller: caller,
		paramTypes: paramTypes,
		emitTypes: emitTypes,
	}
	AllRules = append(AllRules, rule)
	return rule
}


// Emits is part of the Rule interface.
func (rule *RuleImpl) Emits(t reflect.Type) bool {
	found := false
	rule.DoEmitTypes(func(t1 reflect.Type) bool {
		if t1 == t {
			found = true
			return false
		}
		return true
	})
	return found
}

